name: CI
on:
   # События, которые запускают jobs
   push:
      branches: "main"

# jobs запускаются параллельно, если не указана последовательность
jobs:
# Название job вы можете назвать как угодно
   my_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
         # Шаги
      steps:
         # Actions от github: проверяет репозиторий, гит и т.д.
         - uses: actions/checkout@v3
         
         # Пример однолинейного простого скрипта shell
         - name: testing
           run: python -m unittest circle.py square.py triangle.py rectangle.py

   my_job_seconde:
      runs-on: windows-latest
      steps:
         - uses: actions/checkout@v3
         
         - name: install python
           uses: actions/setup-python@v4
           with:
              python-version: '3.9'

         - name: testing
           run: python -m unittest circle.py square.py triangle.py rectangle.py
      
